#!/usr/bin/env python3
"""Uplink monitor — live view of what the uplink transmitter is sending.

Reads the `[up] ...` log that firmware/uplink_transmitter writes to USB
serial, one line per transmitted frame, and serves a page that shows the
frames as they go out:

    python3 uplink_monitor.py --serial /dev/ttyACM0
    python3 uplink_monitor.py --demo                  # no hardware
    # then open http://127.0.0.1:8701

This is the TRANSMITTER side of the bench, run on the computer the Pico is
plugged into. It is deliberately separate from ground_station/server, which
receives the downlink and runs on the Raspberry Pi.

Nothing is stored on disk: the uplink is generated by the bench itself and is
already known from the sketch, so the only thing worth keeping is what is on
the air right now. The record of what the HONEYPOT made of it lives in the CTI
database on the other side of the link.

Only the standard library is required; pyserial is needed solely for --serial.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import threading
import time
from collections import deque
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

HERE = os.path.dirname(os.path.abspath(__file__))
WEB = os.path.join(HERE, "web")

MAX_FRAMES = 400          # ring buffer; ~40 minutes of bench traffic

# Written by firmware/uplink_transmitter:
#   [up] t= 29.3s UNK971 -> HNY1  0x7F_UNKNOWN_OPCODE  foff=+24.0 kHz  \
#        dop=    +0 Hz  probing burst    FCS-BROKEN sent
UP_RE = re.compile(
    r"^\[up\]\s+t=\s*(?P<t>[\d.]+)s\s+(?P<src>\S+)\s*->\s*(?P<dst>\S+)\s+"
    r"(?P<cmd>\S+)\s+foff=\s*(?P<foff>[+-]?[\d.]+)\s*kHz\s+"
    r"dop=\s*(?P<dop>[+-]?[\d.]+)\s*Hz\s+(?P<what>.+?)\s*"
    r"(?P<fcs>FCS-BROKEN)?\s*(?P<st>sent|ERR)\s*$"
)

# The five callsigns the sketch plays as legitimate ground stations; anything
# else on the air is an attacker frame by construction (firmware/uplink_transmitter).
LEGIT_CALLS = {"GS100", "GS102", "GS104", "GS107", "GS109"}


class Feed:
    """Frames seen so far. One lock, because the serial thread writes and the
    HTTP threads read."""

    def __init__(self):
        self.lock = threading.Lock()
        self.frames: deque[dict] = deque(maxlen=MAX_FRAMES)
        self.seq = 0
        self.link = {"port": None, "state": "waiting", "detail": ""}
        self.t0 = time.time()

    def add(self, fr: dict) -> None:
        with self.lock:
            self.seq += 1
            fr["seq"] = self.seq
            fr["ts"] = time.time()
            self.frames.append(fr)

    def set_link(self, state: str, detail: str = "", port: str | None = None):
        with self.lock:
            self.link["state"] = state
            self.link["detail"] = detail
            if port:
                self.link["port"] = port

    def snapshot(self, since: int) -> dict:
        """Everything the page needs: the frames it has not seen yet, plus
        counters recomputed over the whole buffer (cheap at this size)."""
        with self.lock:
            frames = list(self.frames)
            link = dict(self.link)
            seq = self.seq
            uptime = time.time() - self.t0

        by_src: dict[str, dict] = {}
        attacks = fcs_broken = errors = 0
        for f in frames:
            s = by_src.setdefault(f["src"], {"src": f["src"], "count": 0,
                                             "legit": f["legit"], "last": 0.0,
                                             "cmds": {}})
            s["count"] += 1
            s["last"] = f["ts"]
            s["cmds"][f["cmd"]] = s["cmds"].get(f["cmd"], 0) + 1
            if not f["legit"]:
                attacks += 1
            if f["fcs_broken"]:
                fcs_broken += 1
            if f["status"] != "sent":
                errors += 1

        sources = sorted(by_src.values(), key=lambda s: (-s["count"], s["src"]))
        return {
            "link": link,
            "seq": seq,
            "uptime_s": round(uptime, 1),
            "kpis": {
                "frames": len(frames),
                "attacks": attacks,
                "sources": len(by_src),
                "fcs_broken": fcs_broken,
                "errors": errors,
            },
            "sources": sources,
            "frames": [f for f in frames if f["seq"] > since],
        }


FEED = Feed()


def parse_up_line(line: str) -> dict | None:
    m = UP_RE.match(line.strip())
    if not m:
        return None
    src = m.group("src")
    return {
        "t_pass_s": float(m.group("t")),
        "src": src,
        "dst": m.group("dst"),
        "cmd": m.group("cmd"),
        "foff_khz": float(m.group("foff")),
        "dop_hz": float(m.group("dop")),
        "what": m.group("what").strip(),
        "fcs_broken": bool(m.group("fcs")),
        "status": m.group("st"),
        "legit": src in LEGIT_CALLS and m.group("what").strip() == "legit",
    }


def ingest_serial(port: str, baud: int) -> None:
    import serial  # pyserial, only needed here

    while True:
        try:
            with serial.Serial(port, baud, timeout=2) as ser:
                FEED.set_link("connected", f"{port} @ {baud}", port)
                print(f"[uplink] reading {port} @ {baud}")
                buf = b""
                while True:
                    chunk = ser.read(256)
                    buf += chunk
                    while b"\n" in buf:
                        raw, buf = buf.split(b"\n", 1)
                        line = raw.decode("utf-8", "replace").strip()
                        if not line:
                            continue
                        fr = parse_up_line(line)
                        if fr:
                            FEED.add(fr)
                        else:
                            # init banner, warnings — worth showing, not a frame
                            FEED.set_link("connected", line, port)
                            print(f"[pico] {line}")
        except Exception as e:  # unplugged, reflashed, BOOTSEL — wait and retry
            FEED.set_link("offline", str(e), port)
            print(f"[uplink] serial: {e}; retrying in 3 s")
            time.sleep(3)


def ingest_demo() -> None:
    """The sketch's own schedule, without hardware: five stations, one attacker
    frame after each, Doppler following the pass profile."""
    import math

    FEED.set_link("demo", "synthetic traffic, no radio")
    gs = [("GS100", -8.0, "TLM_REQ", 7.0), ("GS102", -4.0, "HK_DUMP", 9.0),
          ("GS104", 0.0, "PING", 5.0), ("GS107", 4.0, "EPS_STATUS", 8.0),
          ("GS109", 8.0, "PASS_SCHEDULE", 11.0)]
    att = [("UNK968", "REBOOT", 28.0, 4.0, "freq+unknown+cmd", False),
           ("GS104", "ERASE_FLASH", 0.0, 4.0, "callsign spoof", False),
           ("UNK971", "0x7F_UNKNOWN_OPCODE", 24.0, 0.9, "probing burst", False),
           ("GS107", "EPS_STATUS", 4.0, 5.0, "doppler spoof", False),
           ("GS102", "HK_DUMP", -4.0, 4.0, "malformed FCS", True)]
    t0, ai = time.time(), 0
    while True:
        for call, foff, cmd, gap in gs:
            t = (time.time() - t0) % 600.0
            dop = -6000.0 * math.sin(math.pi * (t - 300.0) / 600.0 * 2) / 2
            FEED.add({"t_pass_s": round(t, 1), "src": call, "dst": "HNY1",
                      "cmd": cmd, "foff_khz": foff, "dop_hz": round(dop),
                      "what": "legit", "fcs_broken": False, "status": "sent",
                      "legit": True})
            time.sleep(gap)
            a = att[ai % len(att)]; ai += 1
            FEED.add({"t_pass_s": round((time.time() - t0) % 600.0, 1),
                      "src": a[0], "dst": "HNY1", "cmd": a[1],
                      "foff_khz": a[2], "dop_hz": 0.0, "what": a[4],
                      "fcs_broken": a[5], "status": "sent", "legit": False})
            time.sleep(a[3])


# ── http ─────────────────────────────────────────────────────────────────

class Handler(BaseHTTPRequestHandler):
    def log_message(self, *a):
        pass

    def _send(self, body: bytes, ctype: str, code: int = 200):
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        if self.path.startswith("/api/uplink"):
            since = 0
            if "?" in self.path:
                q = self.path.split("?", 1)[1]
                for part in q.split("&"):
                    if part.startswith("since="):
                        try:
                            since = int(part[6:])
                        except ValueError:
                            since = 0
            self._send(json.dumps(FEED.snapshot(since)).encode(),
                       "application/json")
            return
        name = {"/": "uplink.html"}.get(self.path, self.path.lstrip("/"))
        path = os.path.normpath(os.path.join(WEB, name))
        if not path.startswith(WEB) or not os.path.isfile(path):
            self._send(b"not found", "text/plain", 404)
            return
        ctype = {".html": "text/html; charset=utf-8", ".css": "text/css",
                 ".js": "text/javascript"}.get(
            os.path.splitext(path)[1], "application/octet-stream")
        with open(path, "rb") as f:
            self._send(f.read(), ctype)


def main():
    ap = argparse.ArgumentParser(description="live view of the bench uplink")
    ap.add_argument("--serial", help="e.g. /dev/ttyACM0")
    ap.add_argument("--baud", type=int, default=115200)
    ap.add_argument("--demo", action="store_true",
                    help="synthetic traffic, no radio")
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--port", type=int, default=8701)
    args = ap.parse_args()

    if args.demo:
        threading.Thread(target=ingest_demo, daemon=True).start()
    elif args.serial:
        threading.Thread(target=ingest_serial,
                         args=(args.serial, args.baud), daemon=True).start()
    else:
        ap.error("give --serial <port> or --demo")

    srv = ThreadingHTTPServer((args.host, args.port), Handler)
    print(f"[uplink] http://{args.host}:{args.port}")
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
